http:
  port: 5007

database: 
  url: "postgres://interslavic:interslavic@interslavic-db:5432/interslavic?sslmode=disable"

logging:
  dir: "./logs" # MUST BE STRING, PATH TO SAVE LOG
  enable: true # MUST BE BOOL.   
  level: "DEBUG" # MUST BE STRING. Available levels: INFO, WARNING, ERROR. DEFAULT: INFO
  format: "LOG" # MUST BE STRING. Available formats: TXT, JSON. DEFAULT: TXT
  saving_days: 10 # MUST BE INTEGER AND MINIMAL VALUE IS 1.

jwt:
  secret_key: "your-secret-key-change-in-production"